-- Central tuning table. Every system reads from here so the game can be
-- rebalanced without touching logic code.

local Config = {}

Config.Maze = {
	CellSize = 14,
	GridWidth = 13,
	GridHeight = 13,
	WallHeight = 12,
	WallThickness = 1,
	LoopChance = 0.14, -- chance an extra wall is knocked down after generation, adding shortcuts
	MainCorridorEvery = 3, -- every Nth row/column is a wide "main aisle" Thomas can use
}

Config.Lighting = {
	Brightness = 1,
	Ambient = Color3.fromRGB(46, 46, 54),
	OutdoorAmbient = Color3.fromRGB(30, 30, 38),
	ColorShift_Bottom = Color3.fromRGB(20, 20, 30),
	FogColor = Color3.fromRGB(18, 18, 24),
	FogStart = 24,
	FogEnd = 150,
	ExposureCompensation = -0.2,
	FixtureRange = 22,
	FixtureBrightness = 2.2,
	FixtureColor = Color3.fromRGB(255, 238, 200),
	FixtureFrequency = 3, -- roughly 1 in N cells gets a working ceiling fixture; rest stay dim
	DeadFixtureFlickerChance = 0.35,
}

Config.Round = {
	MinPlayers = 1,
	IntermissionTime = 15,
	RespawnInvulnerability = 3,
	ResultsScreenTime = 14,
	JumpscareDuration = 2.6,
	MaxRoundTime = 600,
}

Config.Player = {
	WalkSpeed = 16,
	SprintSpeed = 25,
}

Config.Monsters = {
	{
		id = "George",
		displayName = "Curious George",
		color = Color3.fromRGB(120, 78, 42),
		accentColor = Color3.fromRGB(230, 220, 190),
		scale = 1,
		patrolSpeed = 14,
		chaseSpeed = 24,
		investigateSpeed = 17,
		sightRange = 46,
		sightAngle = 65,
		hearingRadius = 20,
		loseSightTime = 4,
		repathInterval = 0.4,
		quirk = "erratic",
		jumpscareColor = Color3.fromRGB(120, 78, 42),
		flavor = "Insatiably curious. Unfortunately, currently curious about your skull.",
	},
	{
		id = "Peppa",
		displayName = "Peppa Pig",
		color = Color3.fromRGB(235, 150, 170),
		accentColor = Color3.fromRGB(255, 255, 255),
		scale = 0.9,
		patrolSpeed = 12,
		chaseSpeed = 20,
		investigateSpeed = 15,
		sightRange = 40,
		sightAngle = 70,
		hearingRadius = 18,
		loseSightTime = 3.5,
		repathInterval = 0.4,
		quirk = "snortBurst",
		jumpscareColor = Color3.fromRGB(235, 150, 170),
		flavor = "She has found a muddy puddle. She would like you to join her. Permanently.",
	},
	{
		id = "Thomas",
		displayName = "Thomas the Tank Engine",
		color = Color3.fromRGB(20, 90, 160),
		accentColor = Color3.fromRGB(200, 30, 30),
		scale = 1.3,
		patrolSpeed = 16,
		chaseSpeed = 32,
		investigateSpeed = 20,
		sightRange = 55,
		sightAngle = 50,
		hearingRadius = 26,
		loseSightTime = 5,
		repathInterval = 0.5,
		quirk = "railOnly",
		jumpscareColor = Color3.fromRGB(20, 90, 160),
		flavor = "A really useful engine. Useful for absolutely flattening you.",
	},
	{
		id = "Barney",
		displayName = "Barney",
		color = Color3.fromRGB(110, 40, 140),
		accentColor = Color3.fromRGB(60, 200, 90),
		scale = 1.6,
		patrolSpeed = 10,
		chaseSpeed = 17,
		investigateSpeed = 12,
		sightRange = 35,
		sightAngle = 80,
		hearingRadius = 30,
		loseSightTime = 5,
		repathInterval = 0.5,
		quirk = "stomper",
		jumpscareColor = Color3.fromRGB(110, 40, 140),
		flavor = "He loves you. You do not love him back.",
	},
	{
		id = "Grinch",
		displayName = "The Grinch",
		color = Color3.fromRGB(60, 130, 70),
		accentColor = Color3.fromRGB(200, 40, 40),
		scale = 1.05,
		patrolSpeed = 15,
		chaseSpeed = 23,
		investigateSpeed = 17,
		sightRange = 42,
		sightAngle = 65,
		hearingRadius = 20,
		loseSightTime = 4,
		repathInterval = 0.4,
		quirk = "darkBoost",
		jumpscareColor = Color3.fromRGB(60, 130, 70),
		flavor = "His heart grew three sizes today. So did his appetite for chaos.",
	},
	{
		id = "Po",
		displayName = "Kung Fu Panda",
		color = Color3.fromRGB(28, 28, 28),
		accentColor = Color3.fromRGB(240, 240, 240),
		scale = 1.15,
		patrolSpeed = 13,
		chaseSpeed = 21,
		investigateSpeed = 16,
		sightRange = 38,
		sightAngle = 65,
		hearingRadius = 19,
		loseSightTime = 4,
		repathInterval = 0.4,
		quirk = "rollDash",
		jumpscareColor = Color3.fromRGB(28, 28, 28),
		flavor = "There is no charge for awesomeness. Or for what happens next.",
	},
	{
		id = "SpongeBob",
		displayName = "SpongeBob SquarePants",
		color = Color3.fromRGB(235, 210, 60),
		accentColor = Color3.fromRGB(120, 190, 230),
		scale = 0.95,
		patrolSpeed = 13,
		chaseSpeed = 19,
		investigateSpeed = 14,
		sightRange = 36,
		sightAngle = 75,
		hearingRadius = 22,
		loseSightTime = 3.5,
		repathInterval = 0.4,
		quirk = "giggler",
		jumpscareColor = Color3.fromRGB(235, 210, 60),
		flavor = "He is ready. He was born ready. Are you?",
	},
	{
		id = "Dora",
		displayName = "Dora",
		color = Color3.fromRGB(150, 60, 130),
		accentColor = Color3.fromRGB(255, 200, 60),
		scale = 0.95,
		patrolSpeed = 13,
		chaseSpeed = 20,
		investigateSpeed = 15,
		sightRange = 40,
		sightAngle = 70,
		hearingRadius = 20,
		loseSightTime = 4,
		repathInterval = 0.4,
		quirk = "callout",
		jumpscareColor = Color3.fromRGB(150, 60, 130),
		flavor = "She sees you. She is telling EVERYONE she sees you.",
	},
}

Config.Minigames = {
	{
		id = "RestockShelves",
		stationName = "Restock: Aisle of Regret",
		description = "Match falling boxes to the correct shelf slot before time runs out.",
		duration = 16,
		roundsToWin = 8,
		noiseInterval = 2.5,
		noiseRadius = 55,
	},
	{
		id = "FlatPackAssembly",
		stationName = "Flat-Pack Rage Build",
		description = "Repeat the build sequence exactly. One wrong panel and you start over.",
		duration = 18,
		roundsToWin = 5,
		noiseInterval = 2.5,
		noiseRadius = 55,
	},
	{
		id = "SelfCheckout",
		stationName = "Self-Checkout Vibe Check",
		description = "Hold the scanner steady in the green zone. It will not make this easy.",
		duration = 14,
		roundsToWin = 10,
		noiseInterval = 2,
		noiseRadius = 60,
	},
}

Config.AisleSigns = {
	"GRÖNKVIST", "GNORPFJÄLL", "BLÖRD", "SKUGGVASK", "FNURKA",
	"GRUNTSTAD", "MÖRKHUS", "VÄNTAKORV", "SLAPPFJORD", "GNARBÖRK",
	"DÖVSKÅP", "TRUBBEL", "HÖLKSTAD", "BJÖRKÄNGEN", "SKRIKMOSS",
}

return Config
